# Generated by Django 5.2.9 on 2025-12-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
