# Generated by Django 5.2.9 on 2025-12-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='color',
        ),
    ]
